version: "3.8"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=choto
      - POSTGRES_PASSWORD=chotopwd
    ports:
      - "5432:5432"
    volumes:
      - ./pg_db:/var/lib/postgresql/data
